name: Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update Dependencies
      run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        
    - name: Running migration
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate:fresh
      id: migrations
      
    - name: Seeding Database
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        GAPS_USERNAME: ${{ secrets.GAPS_USERNAME }}
        GAPS_PASSWORD: ${{ secrets.GAPS_PASSWORD }}
        TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
        PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
        PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
      run: php artisan db:seed
      id: seeding
      
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        GAPS_USERNAME: ${{ secrets.GAPS_USERNAME }}
        GAPS_PASSWORD: ${{ secrets.GAPS_PASSWORD }}
        PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
        PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
      run: vendor/bin/phpunit
      id: tests
      

      
    - name: send telegram message on push
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            ❌❌❌ A COMMIT DIDN'T PASS THE TEST IN LARAVEL ❌❌❌
            
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          
  
            
  confirmation:
        runs-on: ubuntu-latest
        needs: laravel-tests
        if: false
        steps:
        - name: send telegram message on push
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_CHAT_ID }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
                ✅✅✅ A COMMIT WAS DONE. ✅✅✅

                ${{ github.actor }} created commit:
                Commit message: ${{ github.event.commits[0].message }}

                Repository: ${{ github.repository }}

                See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
